= Message Exchange Over Web Sockets 🐈

This crate implements the simple pattern needed for implementing
service-to-service message exchange over WebSocket connections. Users of meows
can handle typed JSON message with the option for a default handler for any
un-typed messages.

Meows is built on top of link:https://github.com/stjepang/smol[smol] for async
websocket handling behavior. This makes Meows compatible with other smol-based
applications, including those using
link:https://github.com/async-rs/async-std[async-std] 1.6.0 or later.

All messages intended to be handled must be wrapped in a meows appropriate
envelope described below:

.Envelope
[source,json]
----
{
    "type" : "ping",
    "value" : {
        "msg" : "Hey kitty kitty"
    }
}
----

Which will then be mapped to a struct such as:

.Rust code
[source,rust]
----
#[derive(Debug, Deserialize, Serialize)]
struct Ping {
    msg: String,
}
----

In essence, anything that serde can deserialize, can be passed through meows.


== Example

There are examples in the `examples/` directory, here's a simple message handler:

.Meows Server
[source,rust]
----
use log::*;
use meows::*;
use smol;

async fn handle_ping(mut req: Request<()>) -> Option<Message> {
    if let Some(ping) = req.from_value::<Ping>() {
        info!("Ping received: {:?}", ping);
    }
    Some(Message::text("pong"))
}

fn main() -> Result<(), std::io::Error> {
    meows!("ping" => Ping);

    info!("Starting simple ping/pong websocket server with meows");
    let mut server = meows::Server::new();
    server.on("ping", handle_ping);

    smol::run(async move {
        server.serve("127.0.0.1:8105".to_string()).await
    })
}
----


== Contributing

Meows is a typical Rust project, e.g. `cargo build` and `cargo test` will do
most everything you would need to do.

There aren't nearly enough tests, helping with that would certainly be
appreciated :)
